"""Bringing the schema up to date at startup.

``create_all`` was right while the schema was append-only: it is one line, it
needs no tooling, and adding a table beside the old ones cannot damage data.
That stopped being true once columns started changing shape, so the migrations
are now the source of truth and this is what applies them.

``create_all`` remains as a fallback for the one case it is still correct in: a
checkout without Alembic installed, running against a throwaway database. It
logs loudly when it happens, because silently building a schema that no
migration describes is exactly the drift ``tests/test_migrations.py`` exists to
catch.
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger("astrasynth.migrate")

BACKEND_ROOT = Path(__file__).resolve().parent.parent.parent


def _alembic_config(database_url: str):
    from alembic.config import Config

    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_ROOT / "alembic"))
    config.set_main_option("sqlalchemy.url", database_url)
    return config


def _adopt_existing_schema(database_url: str) -> bool:
    """Stamp a database that predates Alembic, if its schema is already current.

    A database built by the old ``create_all`` has every table and no
    ``alembic_version`` row, so a plain ``upgrade head`` tries to create tables
    that exist and dies. The fix is to record that it is already at head rather
    than to re-run the migration.

    Stamping blind would be reckless. It is safe *here*, and only here, because
    the initial migration was autogenerated from the same models ``create_all``
    builds from, and ``tests/test_migrations.py::test_models_and_migrations_agree``
    asserts on every run that the two still describe the same schema. Take that
    test away and this becomes a guess.

    Returns True if it stamped.
    """
    from sqlalchemy import create_engine, inspect

    from alembic import command

    engine = create_engine(database_url)
    try:
        inspector = inspect(engine)
        tables = set(inspector.get_table_names())
    finally:
        engine.dispose()

    if "alembic_version" in tables or "missions" not in tables:
        return False

    logger.warning(
        "database has a schema but no migration history; stamping it at head. "
        "This is correct only because the initial migration was generated from "
        "these models and the drift test proves they still agree."
    )
    command.stamp(_alembic_config(database_url), "head")
    return True


def upgrade_to_head(database_url: str) -> str:
    """Apply outstanding migrations. Returns the revision now in place.

    Safe to run on every boot: with nothing outstanding it is one query against
    ``alembic_version``. Safe to run from several processes at once, because the
    migration runs inside a transaction and PostgreSQL takes DDL locks - a second
    process either waits or finds the work already done.
    """
    from sqlalchemy import create_engine

    from alembic import command
    from alembic.migration import MigrationContext

    _adopt_existing_schema(database_url)
    command.upgrade(_alembic_config(database_url), "head")

    engine = create_engine(database_url)
    try:
        with engine.connect() as connection:
            return MigrationContext.configure(connection).get_current_revision() or "unknown"
    finally:
        engine.dispose()


def prepare_schema(database_url: str, auto_migrate: bool) -> None:
    from app.db.session import Base, engine

    if not auto_migrate:
        logger.info("auto_migrate is off; assuming the schema is already current")
        return

    try:
        revision = upgrade_to_head(database_url)
        logger.info("schema at revision %s", revision)
    except ImportError:
        logger.warning(
            "alembic is not installed; falling back to create_all. This builds a "
            "schema no migration describes - install alembic before deploying."
        )
        Base.metadata.create_all(bind=engine)
