"""initial schema"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30be9b387be3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "missions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("terrain_image_path", sa.String(length=500), nullable=False),
        sa.Column("terrain_source", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rover_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("battery_capacity_kwh", sa.Float(), nullable=False),
        sa.Column("max_traversable_slope_deg", sa.Float(), nullable=False),
        sa.Column("energy_per_meter_kwh", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "experiments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mission_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("failure_mode", sa.String(length=40), nullable=True),
        sa.Column("reason", sa.String(length=1000), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("code_revision", sa.String(length=64), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("runtime_seconds", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_experiments_mission_id"), "experiments", ["mission_id"], unique=False)
    op.create_index(
        "ix_experiments_mission_kind", "experiments", ["mission_id", "kind"], unique=False
    )
    op.create_table(
        "rover_paths",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mission_id", sa.UUID(), nullable=False),
        sa.Column("rover_config_id", sa.UUID(), nullable=False),
        sa.Column("start_point", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("end_point", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("waypoints", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_distance_m", sa.Float(), nullable=True),
        sa.Column("total_energy_cost_kwh", sa.Float(), nullable=True),
        sa.Column("algorithm_used", sa.String(length=30), nullable=False),
        sa.Column("planner_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("planned_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rover_config_id"],
            ["rover_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rover_paths_mission_id"), "rover_paths", ["mission_id"], unique=False)
    op.create_table(
        "science_targets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mission_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("observation_seconds", sa.Float(), nullable=False),
        sa.Column("required_instrument", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_science_targets_mission_id"), "science_targets", ["mission_id"], unique=False
    )
    op.create_table(
        "terrain_analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mission_id", sa.UUID(), nullable=False),
        sa.Column("slope_map_path", sa.String(length=500), nullable=True),
        sa.Column("obstacle_contours", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("terrain_classification", sa.String(length=50), nullable=True),
        sa.Column("hazard_heatmap_path", sa.String(length=500), nullable=True),
        sa.Column("uncertainty_map_path", sa.String(length=500), nullable=True),
        sa.Column("analysis_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_terrain_analyses_mission_id"), "terrain_analyses", ["mission_id"], unique=False
    )
    op.create_table(
        "traverse_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mission_id", sa.UUID(), nullable=False),
        sa.Column("rover_config_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("failure_mode", sa.String(length=40), nullable=True),
        sa.Column("reason", sa.String(length=1000), nullable=True),
        sa.Column("start_point", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("goal_point", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("distance_m", sa.Float(), nullable=False),
        sa.Column("energy_kwh", sa.Float(), nullable=False),
        sa.Column("elapsed_seconds", sa.Float(), nullable=False),
        sa.Column("replans", sa.Integer(), nullable=False),
        sa.Column("reroutes", sa.Integer(), nullable=False),
        sa.Column("repair_expansions", sa.Integer(), nullable=False),
        sa.Column("initial_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("executed_path", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("events", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("belief_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["rover_config_id"],
            ["rover_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_traverse_runs_mission_id"), "traverse_runs", ["mission_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mission_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("progress_detail", sa.String(length=200), nullable=True),
        sa.Column("experiment_id", sa.UUID(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("claimed_by", sa.String(length=80), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["mission_id"], ["missions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_mission_id"), "jobs", ["mission_id"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "mission_risk_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mission_id", sa.UUID(), nullable=False),
        sa.Column("rover_path_id", sa.UUID(), nullable=False),
        sa.Column("risk_score", sa.String(length=20), nullable=True),
        sa.Column("feasibility", sa.String(length=30), nullable=True),
        sa.Column("structured_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ai_narrative", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("narrative_source", sa.String(length=20), nullable=True),
        sa.Column("generated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rover_path_id"],
            ["rover_paths.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mission_risk_reports_mission_id"),
        "mission_risk_reports",
        ["mission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mission_risk_reports_rover_path_id"),
        "mission_risk_reports",
        ["rover_path_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mission_risk_reports_rover_path_id"), table_name="mission_risk_reports")
    op.drop_index(op.f("ix_mission_risk_reports_mission_id"), table_name="mission_risk_reports")
    op.drop_table("mission_risk_reports")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_mission_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_traverse_runs_mission_id"), table_name="traverse_runs")
    op.drop_table("traverse_runs")
    op.drop_index(op.f("ix_terrain_analyses_mission_id"), table_name="terrain_analyses")
    op.drop_table("terrain_analyses")
    op.drop_index(op.f("ix_science_targets_mission_id"), table_name="science_targets")
    op.drop_table("science_targets")
    op.drop_index(op.f("ix_rover_paths_mission_id"), table_name="rover_paths")
    op.drop_table("rover_paths")
    op.drop_index("ix_experiments_mission_kind", table_name="experiments")
    op.drop_index(op.f("ix_experiments_mission_id"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_table("rover_configs")
    op.drop_table("missions")
    # ### end Alembic commands ###
